<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postal_code</name>
   <tag></tag>
   <elementGuidId>ecaf95d5-6896-407f-a812-4e7025befd44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div/input[@id=&quot;postal-code&quot;])</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
